services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:latest
    volumes:
      - ./temp:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ismobot
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust