FROM python:3.12
LABEL authors="laziz"

COPY . /app
WORKDIR /app

ENV TOKEN=${TOKEN}
ENV ADMIN_ID=${ADMIN_ID}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASS=${DB_PASS}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV INSTAGRAM_URL=${INSTAGRAM_URL}
ENV CARD_NUMBER=${CARD_NUMBER}

RUN pip3 install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python3", "main.py"]